import { v4 as uuidv4 } from 'uuid';
const inventory = [{ id: uuidv4(),
    name: "item 1 to sell",
    img: "image source",
    price: 82.00,
    qty: 0,
   },
   { id: uuidv4(),
    name: "item 2 to sell",
    img: "image source",
    price: 69.00,
    qty: 0,
   },
   { id: uuidv4(),
    name: "item 3 to sell",
    img: "image source",
    price: 65.00,
    qty: 0,
   },
   { id: uuidv4(),
    name: "item 4 to sell",
    img: "image source",
    price: 65.00,
    qty: 0
   },
   { id: uuidv4(),
    name: "item 5 to sell",
    img: "image source",
    price: 41.00,
    qty: 0,
   },
   { id: uuidv4(),
    name: "item 6 to sell",
    img: "image source",
    price: 61.00,
    qty: 0,
   },
   { id: uuidv4(),
    name: "item 7 to sell",
    img: "image source",
    price: 14.00,
    qty: 0,
   },
   { id: uuidv4(),
    name: "item 8 to sell",
    img: "image source",
    price: 14.00,
    qty: 0,
   }
];

export default inventory;